Reconfigure zone for cluster

diff --git a/kubeflow-gcp/.hub/configure b/kubeflow-gcp/.hub/configure
--- a/kubeflow-gcp/.hub/configure
+++ b/kubeflow-gcp/.hub/configure
@@ -18,12 +18,23 @@ if ! dotenv contains "GOOGLE_GKE_CLUSTER"; then
   zone="$(dotenv get GOOGLE_ZONE)"
 
   echo "* List of GKE clusters"
-  gcloud container clusters list --zone "$zone" | ident | color g
+  gcloud container clusters list | ident | color g
   ask env "GOOGLE_GKE_CLUSTER" --message 'gke cluster name (for possible values see above)' -random -empty
   cluster_name="$(dotenv get "GOOGLE_GKE_CLUSTER")"
 
   echo "* Fetching kubeconfig credentials"
-  gcloud container clusters get-credentials "$cluster_name" --zone "$zone" | ident || true
+  zone="$(gcloud container clusters list --format json | jq --arg cluster "$cluster_name" -cMr 'first|.zone | select(.)')"
+  if test -z "$zone"; then
+    gcloud container clusters get-credentials "$cluster_name" --zone "$zone" | ident || true
+    echo "Adjusting region and zone from cluster: $cluster_name"
+    dotenv set "$GOOGLE_ZONE" "$zone"
+    dotenv set "$GOOGLE_REGION" "$(echo "$zone" | cut -d- -f1-2)"
+  else
+    echo "Error: cluster $cluster_name doesn't have zone"
+    echo "We do not support this yet. Please contact our support team"
+    exit 1
+  fi
+
 fi
 
 
