Harmonizing parameters for Kubeflow rancher deployment epam/hub-kubeflow-components#25

diff --git a/kubeflow-rancher/bin/check-cluster b/kubeflow-rancher/bin/check-cluster
--- a/kubeflow-rancher/bin/check-cluster
+++ b/kubeflow-rancher/bin/check-cluster
@@ -1,5 +1,16 @@
 #!/bin/bash -e
 
+hubctl="$(which hubctl 2>/dev/null || true)"
+if test -z "$hubctl"; then
+  # backward compatibility
+  color warn "CLI name 'hub' is deprecated. It will be renamed to 'hubctl' in future releases"
+  hubctl="$(which hub 2>/dev/null || true)"
+fi
+if test -z "$hubctl"; then
+  color error "hubctl not found in PATH. Please install hubctl first."
+  exit 1
+fi
+
 beginswith() {
   case $2 in "$1"*) true;; *) false;; esac;
 }
@@ -12,13 +23,13 @@ in_directory() {
 
 if ! dotenv contains HUB_KUBECONFIG; then
   color warning "HUB_KUBECONFIG is not set"
-  hub stack configure -r "kubernetes"
+  $hubctl stack configure -r "kubernetes"
 fi
 
 hub_kubeconfig="$(dotenv get HUB_KUBECONFIG)"
 if ! test -f "$hub_kubeconfig"; then
   color warn "Cannot find kubeconfig: $hub_kubeconfig"
-  hub stack configure -r "kubernetes"
+  $hubctl stack configure -r "kubernetes"
 fi
 
 test_connection() {
@@ -40,7 +51,7 @@ if ! test_connection "$hub_kubeconfig"; then
   echo "  Removing: $hub_kubeconfig"
   rm -f "$hub_kubeconfig"
   dotenv set "HUB_KUBECONFIG" ""
-  hub stack configure -r "kubernetes"
+  $hubctl stack configure -r "kubernetes"
   echo -n "* Rechecking cluster connectivity: "
   if test_connection "$hub_kubeconfig"; then
     color green "ok"
